### PR TITLE
viking: Add `--version=` argument

### PR DESCRIPTION
**Pull request by MonsterDruide1**
This PR adds the argument of `--version=` into the toolset, which can be used when multiple versions of the game should be decompiled.

When not specified, the program will execute as it has been before. When specified, it requires the files to be set up in a slightly different way (example for version `1.0`):
- `build` has to be moved to `build-1.0`
- `tools/config.toml`s `function_csv` has to contain a placeholder for `version`, so it looks like this: `"data/game_functions-{version}.csv`
- The function CSV has to follow the same naming scheme
- As the original code for different version differs as well, `main-1.0.elf` is required.

---
This change is [Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5)

### CODE REVIEW

**Comment by leoetlino** [comment]
Uh, why not just use build-{version} and data-{version} for consistency? Or even build/{version} and data/{version} to avoid cluttering up the repo root.

**Comment by MonsterDruide1** [comment]
Oh, good idea!
I'd go for `data/VERSION/...` and `build/VERSION/...` to keep the root files to a minimum. Changed the code accordingly.
The function-csv path has to be set properly in `config.toml`.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[viking/src/elf.rs, line 107 at r1](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-Mn7igGY8bLemuzLHK8L-r1-107:-MnrEBN59F_QqIyOdMZQ:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/e20b5e6357aefb3e5a8a6171c7235d8c00dda8c9/viking/src/elf.rs#L107)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

IMO it'd be more readable to write this with an `if` block or with pattern matching.
</blockquote></details>

Done.
___
*[viking/src/tools/check.rs, line 181 at r1](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-Mn7igGY8bLemuzLHK8N-r1-181:-MnrEOLF4DeS2_fWjwVZ:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/e20b5e6357aefb3e5a8a6171c7235d8c00dda8c9/viking/src/tools/check.rs#L181)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

```suggestion
        .map(|s| s.clone().replace("--version=", ""))
```
</blockquote></details>

Done.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[viking/src/functions.rs, line 170 at r1](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-Mn7igGY8bLemuzLHK8M-r1-170:-MnrGF4b9CJM27xLtCqU:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/e20b5e6357aefb3e5a8a6171c7235d8c00dda8c9/viking/src/functions.rs#L170)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Please do not introduce new static mutable state. It'd be cleaner to take the version as an argument in `get_functions` and `write_functions`. Recomputing the function CSV path isn't expensive (compared to walking through every function).
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
also make sure to run clippy and that no new lint issues are introduced

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-:-MnrkdpzDDd6ajCEpeUK:b47kg2r)* status: all files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1)

___
*[viking/src/elf.rs, line 105 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-Mnrk4uO6qGikDxMXMx6:-Mnrk4uO6qGikDxMXMx7:bwryj6u) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/elf.rs#L105)):*
> ```XML
> }
> 
> pub fn load_orig_elf(version: &Option<String>) -> Result<OwnedElf> {
> ```

`version` should be `&Option<&str>` -- there is no reason to force the caller to make a (heap-allocated) String.
___
*[viking/src/elf.rs, line 117 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkJYN1HDfeiCb0Bhk:-MnrkJYN1HDfeiCb0Bhl:b-ej6sca) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/elf.rs#L117)):*
> ```XML
> }
> 
> pub fn load_decomp_elf(version: &Option<String>) -> Result<OwnedElf> {
> ```

same remark about `version` here
___
*[viking/src/functions.rs, line 167 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkO943uG-qnatfe8_:-MnrkO943uG-qnatfe8a:b-ej6sca) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/functions.rs#L167)):*
> ```XML
> }
> 
> pub fn get_functions_csv_path(version: &Option<String>) -> PathBuf {
> ```

same remark about `version` here
___
*[viking/src/functions.rs, line 177 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkPGv7W_-0tfFCKuu:-MnrkPGv7W_-0tfFCKuv:b-ej6sca) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/functions.rs#L177)):*
> ```XML
> 
> /// Returns a Vec of all known functions in the executable.
> pub fn get_functions(version: &Option<String>) -> Result<Vec<Info>> {
> ```

same remark about `version` here
___
*[viking/src/functions.rs, line 181 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkPiK70cuFj1bFi5j:-MnrkPiL3Hp2Zc2Mhtx1:b-ej6sca) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/functions.rs#L181)):*
> ```XML
> }
> 
> pub fn write_functions(functions: &[Info], version: &Option<String>) -> Result<()> {
> ```

same remark about `version` here
___
*[viking/src/tools/check.rs, line 203 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkY_fDzTESzm60rln:-MnrkY_fDzTESzm60rlo:b-ej6sca) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/tools/check.rs#L203)):*
> ```XML
>     decomp_symtab: &elf::SymbolTableByName,
>     args: &Vec<String>,
>     version: &Option<String>
> ```

same remark about `version` here

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @leoetlino)

___
*[viking/src/elf.rs, line 105 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-Mnrk4uO6qGikDxMXMx6:-MoNuJg_2wvtcmb58tz_:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/elf.rs#L105)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`version` should be `&Option<&str>` -- there is no reason to force the caller to make a (heap-allocated) String.
</blockquote></details>

Done.
___
*[viking/src/elf.rs, line 117 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkJYN1HDfeiCb0Bhk:-MoNuMpxCFGGkfXrD6aj:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/elf.rs#L117)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

same remark about `version` here
</blockquote></details>

Done.
___
*[viking/src/functions.rs, line 167 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkO943uG-qnatfe8_:-MoNuO5F-noeFkx6pPBC:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/functions.rs#L167)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

same remark about `version` here
</blockquote></details>

Done.
___
*[viking/src/functions.rs, line 177 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkPGv7W_-0tfFCKuu:-MoNuOKw2pq1_Q8NKTcT:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/functions.rs#L177)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

same remark about `version` here
</blockquote></details>

Done.
___
*[viking/src/functions.rs, line 181 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkPiK70cuFj1bFi5j:-MoNuOm99qImTrhLhHFh:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/functions.rs#L181)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

same remark about `version` here
</blockquote></details>

Done.
___
*[viking/src/tools/check.rs, line 203 at r2](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-MnrkY_fDzTESzm60rln:-MoNuQ4J-1g1DIBVE9Ua:b-896fix) ([raw file](https://github.com/open-ead/nx-decomp-tools/blob/ca4aa99f5376e5093cf0a4ae5ea0ee50eb43d542/viking/src/tools/check.rs#L203)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

same remark about `version` here
</blockquote></details>

Done.

**Review by MonsterDruide1 — COMMENTED** [review]
Done, `clippy` doesn't complain about anything anymore.
How can I check for lint issues?

> *[Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-:-MoNx03Q2qoOvkL3Ua1d:b-5tovxh)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @leoetlino)

**Review by leoetlino — APPROVED** [review]
Clippy *is* the linter.

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nx-decomp-tools/5#-:-MoNyO1C4koM3InrKtR9:bonktif)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Pull request merged**
